#ifndef __INIT_INTERRUPT_REGISTERS_H
#define __INIT_INTERRUPT_REGISTERS_H

enum {
  INTERRUPT_REG_BASE = 0xB000,

  IRQ_BASIC_PENDING  = INTERRUPT_REG_BASE + 0x200,
  IRQ_PENDING_1      = INTERRUPT_REG_BASE + 0x204,
  IRQ_PENDING_2      = INTERRUPT_REG_BASE + 0x208,
  FIQ_CONTROL        = INTERRUPT_REG_BASE + 0x20C,
  ENABLE_IRQS_1      = INTERRUPT_REG_BASE + 0x210,
  ENABLE_IRQS_2      = INTERRUPT_REG_BASE + 0x214,
  ENABLE_BASIC_IRQS  = INTERRUPT_REG_BASE + 0x218,
  DISABLE_IRQS_1     = INTERRUPT_REG_BASE + 0x21C,
  DISABLE_IRQS_2     = INTERRUPT_REG_BASE + 0x220,
  DISABLE_BASIC_IRQS = INTERRUPT_REG_BASE + 0x224,
};


#endif // !__INIT_INTERRUPT_REGISTERS_H

